name: Test

on:
  push:
  pull_request:

jobs:
  local-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        shell: pwsh
        run: .\build.ps1 -Test
